import Head from 'next/head';
import Sidebar from '@/components/Sidebar';
import Header from '@/components/Header';
import Feed from '@/components/Feed';
import Widgets from '@/components/Widgets';

export default function Home() {
  return (
    <>
      <Head>
        <title>Facebook</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      {/** Header */}
      <Header />
      <main>
        <main className='flex bg-gray-100'>
          {/** sidebar */}
          <Sidebar />
          <Feed />
          {/** Widgets */}
          <Widgets />
        </main>
      </main>
    </>
  );
}
